import { defineConfig } from 'vite'
import { viteStaticCopy } from 'vite-plugin-static-copy'
import { resolve } from 'path'
import { createHash } from 'crypto'
import { readFileSync } from 'fs'

const HASHED_SCRIPTS = [
  'style/js/custom-plugins.js',
  'style/js/custom-scripts.js',
]

function cacheBustStaticScripts() {
  return {
    name: 'cache-bust-static-scripts',
    transformIndexHtml: {
      order: 'post',
      handler(html) {
        for (const src of HASHED_SCRIPTS) {
          const content = readFileSync(resolve(__dirname, src))
          const hash = createHash('md5').update(content).digest('hex').slice(0, 8)
          const escaped = src.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
          const pattern = new RegExp(`(<script[^>]*\\bsrc=")(${escaped})(")`)
          html = html.replace(pattern, `$1$2?v=${hash}$3`)
        }
        return html
      },
    },
  }
}

export default defineConfig({
  root: '.',
  publicDir: false, // Don't copy public folder (we manage assets explicitly)

  build: {
    outDir: 'dist',
    emptyOutDir: true,
    cssCodeSplit: false,

    rollupOptions: {
      input: {
        main: resolve(__dirname, 'index.html'),
        '404': resolve(__dirname, '404.html'),
      },

      // Keep vendor JS files external - loaded via script tags
      external: [
        /^style\/js\/bootstrap\.bundle\.min\.js$/,
        /^style\/js\/embla-carousel\.umd\.js$/,
        /^style\/js\/embla-carousel-autoplay\.umd\.js$/,
        /^style\/js\/muuri\.min\.js$/,
      ],

      output: {
        assetFileNames: 'assets/[name]-[hash][extname]',
        chunkFileNames: 'assets/[name]-[hash].js',
        entryFileNames: 'assets/[name]-[hash].js',
      }
    }
  },

  plugins: [
    cacheBustStaticScripts(),
    viteStaticCopy({
      targets: [
        // NOTE: vite-plugin-static-copy v4 preserves the full src path under `dest`
        // (v3 placed a file at dest/<basename>). So `dest` must be '.' here — the src
        // already carries the 'style/js/' or 'style/' prefix. Using dest:'style/js'
        // double-nests to dist/style/js/style/js/... and 404s every script in prod.
        // Copy vendor JS files that should not be bundled
        {
          src: 'style/js/bootstrap.bundle.min.js',
          dest: '.'
        },
        {
          src: 'style/js/muuri.min.js',
          dest: '.'
        },
        // Copy Embla Carousel (Phase 8 - replaced Revolution Slider)
        {
          src: 'style/js/embla-carousel.umd.js',
          dest: '.'
        },
        {
          src: 'style/js/embla-carousel-autoplay.umd.js',
          dest: '.'
        },
        // Copy GLightbox (Phase 8 - replaced LightGallery)
        {
          src: 'style/js/glightbox.min.js',
          dest: '.'
        },
        // Copy custom JS files (Phase 7 - extracted from plugins.js and scripts.js)
        {
          src: 'style/js/custom-plugins.js',
          dest: '.'
        },
        {
          src: 'style/js/custom-scripts.js',
          dest: '.'
        },
        // Copy CSS files
        {
          src: 'style/css',
          dest: '.'
        },
        {
          src: 'style/style.css',
          dest: '.'
        },
        // style/type/ removed from static-copy 2026-05: icon fonts (Slimicons,
        // FontAwesome, elemis, lg) are no longer used (replaced with inline SVG),
        // and Vite bundles the 4 needed Montserrat WOFF2 files into dist/assets/
        // via style/css/fonts.css. The remaining static-copy of style/type/ would
        // have shipped ~7.4MB of dead icon-font binaries to S3.

        // The full images/ originals directory (~70MB of source photos) is no longer
        // copied: nothing on the page references it except images/favicon.ico, and Vite
        // already fingerprints that into dist/assets/ via the <link rel="shortcut icon">
        // in index.html / 404.html. Shipping the originals bloated every deploy artifact
        // and S3 for no user-visible benefit. Everything displayed comes from
        // images-optimized/ (copied below).
        // Copy optimized images directory (AVIF, WebP, JPEG in responsive widths)
        {
          src: 'images-optimized',
          dest: '.'
        },
        // Copy other static files
        {
          src: 'robots.txt',
          dest: '.'
        },
        // llms.txt for AI discoverability
        {
          src: 'llms.txt',
          dest: '.'
        },
        // Note: sitemap.xml is generated by postbuild script
      ]
    })
  ],

  // Dev server configuration
  server: {
    open: true, // Open browser on start
    port: 3000,
  },
})
